# Generated by Django 4.1.4 on 2024-04-12 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(default='', max_length=50)),
                ('PassWord', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=50)),
                ('Prenom', models.CharField(max_length=50)),
                ('Date_Naissance', models.DateField()),
                ('Date_Deces', models.DateField()),
                ('HDM', models.FloatField(default=0)),
                ('Groupe_Sanguin', models.CharField(max_length=4)),
                ('Menopause', models.CharField(max_length=40)),
                ('Type_histo', models.CharField(max_length=40)),
                ('Grade_histo', models.CharField(max_length=40)),
                ('Emboles_vasculaires', models.CharField(max_length=40)),
                ('Class_moleculaire', models.CharField(max_length=40)),
                ('S_types_moleculaires', models.CharField(max_length=40)),
                ('RE', models.CharField(max_length=40)),
                ('RP', models.CharField(max_length=40)),
                ('HER2', models.CharField(max_length=40)),
                ('KI67', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Traitement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Type', models.CharField(max_length=40)),
                ('Id_P', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='btksoapp.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Type', models.CharField(max_length=40)),
                ('Id_P', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='btksoapp.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Antécedants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discription', models.CharField(max_length=100)),
                ('Id_P', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='btksoapp.patient')),
            ],
        ),
    ]
