# Generated by Django 4.1.4 on 2024-04-12 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('btksoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Antécedants',
            new_name='Antecedants',
        ),
    ]
