# Generated by Django 4.1.4 on 2024-06-05 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('btksoapp', '0002_rename_antécedants_antecedants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traitement',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='traitement',
            name='Id_P',
        ),
        migrations.AddField(
            model_name='patient',
            name='Date_Debut_P',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='Date_Fin_P',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='Statut',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Class_moleculaire',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Emboles_vasculaires',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Grade_histo',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Groupe_Sanguin',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='patient',
            name='HER2',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='patient',
            name='KI67',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Menopause',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='patient',
            name='RE',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='patient',
            name='RP',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='patient',
            name='S_types_moleculaires',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Type_histo',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.CreateModel(
            name='Traitement_Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_P', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='btksoapp.patient')),
                ('Id_T', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='btksoapp.traitement')),
            ],
        ),
    ]
