# Generated by Django 4.1.4 on 2024-06-06 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btksoapp', '0003_remove_traitement_date_remove_traitement_id_p_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='Date_Deces',
            field=models.DateField(blank=True),
        ),
    ]
