# Generated by Django 4.1.4 on 2024-06-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btksoapp', '0004_alter_patient_date_deces'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='Date_Deces',
            field=models.DateField(blank=True, null=True),
        ),
    ]
