# Generated by Django 4.1.4 on 2024-06-28 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('btksoapp', '0005_alter_patient_date_deces'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='Class_moleculaire',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='Emboles_vasculaires',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='HDM',
        ),
    ]
