# Generated by Django 4.1.4 on 2024-06-30 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('btksoapp', '0006_remove_patient_class_moleculaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='Id_M',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='btksoapp.medecin'),
        ),
    ]
