# Generated by Django 4.1.4 on 2024-06-30 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('btksoapp', '0007_patient_id_m'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='Id_M',
        ),
        migrations.DeleteModel(
            name='Medecin',
        ),
    ]
