# Generated by Django 4.1.4 on 2024-07-01 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btksoapp', '0009_medecin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medecin',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
