# Generated by Django 4.1.4 on 2024-07-01 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('btksoapp', '0010_alter_medecin_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='Id_M',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
